# Generated by Django 4.2.7 on 2023-12-01 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ExercisePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('workout_time', models.CharField(choices=[('once in a week', 'once in a week'), ('twice in a week', 'twice in a week'), ('daily', 'daily'), ('rarely', 'rarely')], max_length=255)),
                ('preferred_workout_time', models.CharField(choices=[('morning', 'morning'), ('evening', 'evening')], max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='diet_plan', to='plans.dietplan')),
                ('exercise_plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exercise_plan', to='plans.exerciseplan')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_detail', to='plans.userdetails')),
            ],
        ),
    ]
