# Generated by Django 4.2.7 on 2023-12-04 06:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ('-modified_at',)},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-modified_at',)},
        ),
    ]
